version: '3.8'
services:
  # Drilbur
  drilbur:
    container_name: drilbur
    build:
      context: ./drilbur
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://drilbur:3001/']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 0s
    volumes:
      - ./drilbur:/usr/src/drilbur
      - /usr/src/drilbur/node_modules

  # Ralts
  ralts:
    container_name: ralts
    build:
      context: ./ralts
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    depends_on:
      drilbur:
        condition: service_healthy
    volumes:
      - ./ralts:/usr/src/ralts
      - /usr/src/ralts/node_modules

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    # network_mode: bridge
    ports:
      - 6379:6379
