version: '3.8'
services:
  # Drilbur
  drilbur:
    container_name: drilbur
    build:
      context: .
      dockerfile: ./apps/drilbur/.docker/Dockerfile
    env_file:
      - .env
    environment:
      - IS_DOCKER=true
    ports:
      - ${DRILBUR_PORT}:${DRILBUR_PORT}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://drilbur:$DRILBUR_PORT/healthcheck']
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 20s
    volumes:
      - ./apps/drilbur:/app/apps/drilbur
      # - ./apps/drilbur:/app

  # Ralts
  ralts:
    container_name: ralts
    build:
      context: .
      dockerfile: ./apps/ralts/Dockerfile
    command: npm run dev
    env_file:
      - .env
    environment:
      - IS_DOCKER=true
    ports:
      - ${VITE_RALTS_PORT}:${VITE_RALTS_PORT}
    depends_on:
      drilbur:
        condition: service_healthy
    volumes:
      - ./apps/ralts:/app/apps/ralts
      - /app/apps/ralts/node_modules

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    # network_mode: bridge
    ports:
      - 6379:6379

  # Smeargle
  smeargle:
    container_name: smeargle
    build:
      context: .
      dockerfile: ./apps/smeargle/Dockerfile
    command: npm run dev
    env_file:
      - .env
    environment:
      - VITE_IS_DOCKER=true
    ports:
      - ${SMEARGLE_PORT}:${SMEARGLE_PORT}
    volumes:
      - ./apps/smeargle:/app/apps/smeargle
      - /app/apps/smeargle/node_modules

  # Clobbopus
  clobbopus:
    container_name: clobbopus
    build:
      context: .
      dockerfile: ./apps/clobbopus/Dockerfile
    env_file:
      - .env
    ports:
      - ${CLOBBOPUS_PORT}:${CLOBBOPUS_PORT}
    volumes:
      - ./apps/clobbopus:/app/clobbopus
