version: '3.8'
services:
  # Drilbur
  drilbur:
    container_name: drilbur
    build:
      context: .
      dockerfile: ./drilbur/Dockerfile
    ports:
      - '3001:3001'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://drilbur:3001/']
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 0s
    # volumes:
    #   - ./drilbur:/app
    #   - /app/node_modules

  # Ralts
  ralts:
    container_name: ralts
    build:
      context: .
      dockerfile: ./ralts/Dockerfile
    # command: npm run dev
    ports:
      - '3005:3005'
    depends_on:
      drilbur:
        condition: service_healthy
  #   volumes:
  #     - ./ralts:/usr/src/ralts
  #     - /usr/src/ralts/node_modules

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    # network_mode: bridge
    ports:
      - 6379:6379

  # Smeargle
  smeargle:
    container_name: smeargle
    build:
      context: .
      dockerfile: ./smeargle/Dockerfile
    # command: npm run dev
    ports:
      - '3000:3000'
  #   volumes:
  #     - ./smeargle:/usr/src/smeargle
  #     - /usr/src/smeargle/node_modules
